embeddings {
  tensor_name: "fmnist_embedding_1:0"
  metadata_path: "fashionMNIST-logs\\metadata.tsv"
  sprite {
    image_path: "fashionMNIST-logs\\sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
